{% set name = "pytest-sphinx" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_sphinx-{{ version }}.tar.gz
  sha256: bdf45d96458e6aa1f3618c4845e60924eaa91244247c527eb88f58d6685dece6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pytest >=8.1.1

test:
  imports:
    - pytest_sphinx
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Doctest plugin for pytest with support for Sphinx-specific doctest-directives
  home: https://github.com/twmr/pytest-sphinx
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
